feat(spansy): add AsRef<Span<[u8]>> impl for Span<str>
tlsnotary/tlsn-utils pull request #20
Opened 2024-02-05 23:19 UTC by sinui0

This PR impls AsRef<Span<[u8]>> for Span<str>. This adds some flexibility when working with types containing both kinds of spans.

2024-02-07 07:18 UTC, themighty1 requested changes

2024-02-07 07:18 UTC, themighty1 commented on spansy/src/lib.rs
> +        // Span<str> can be safely converted to Span<[u8]> because they have
Is there a guarantee that the `Span` struct is stored in contiguous memory? e.g. what if its `data` field and `indices` field are stored non-contiguously?

2024-02-07 10:16 UTC, th4s approved these changes
:+1:

2024-02-07 22:12 UTC, sinui0 commented on spansy/src/lib.rs
> +        // Span<str> can be safely converted to Span<[u8]> because they have
yes, fields in a struct are stored contiguously in memory

2024-02-08 18:27 UTC, sinui0 commented on spansy/src/lib.rs
> +        // Span<str> can be safely converted to Span<[u8]> because they have
I'm going to proceed with merge, as I'm quite confident this is safe. I've run it past chatgpt a couple times now as well just for sanity checking.

A `Span<str>` is identical to a `Span<[u8]>` from a memory perspective, and from a type perspective it has strictly fewer invariants, eg not assumptions about being valid utf8 sequence. This of course also applies to `&str` to `&[u8]` coercions.

If you have reason to believe otherwise please open an issue

2024-02-08 18:28 UTC, merged