feat(spansy): HTTP body content + parsing
tlsnotary/tlsn-utils pull request #21
Opened 2024-02-05 23:30 UTC by sinui0

This PR adds a `BodyContent` type in the http module, and now attempts to parse the body content if it is recognized. This does not yet support the chunked transfer encoding, that'll come later.

2024-02-07 09:15 UTC, th4s approved these changes
:+1:

2024-02-07 09:15 UTC, th4s commented on spansy/src/http/types.rs
> +    pub content: BodyContent,
If we have a `Body {span, content: BodyContent::Unknown(span)}` we have some redundancy because it contains `span` twice. Shouldn't we fix this? What about implementing `Spanned` for `Body` instead?

2024-02-07 22:18 UTC, sinui0 commented on spansy/src/http/types.rs
> +    pub content: BodyContent,
The span of `content` won't be the same span when the transfer encoding is chunked. The body span will cover the entire body data including framing bytes, whereas body content will not have framing bytes.

2024-02-08 07:29 UTC, themighty1 requested changes

2024-02-08 07:29 UTC, themighty1 commented on spansy/src/http/span.rs
> +            .headers_with_name("Content-Type")
Can we have an assert here that there is only one "Content-Type" header?

2024-02-08 07:29 UTC, themighty1 commented on spansy/src/http/span.rs
> +            .headers_with_name("Content-Type")
ditto

2024-02-08 07:29 UTC, themighty1 commented on spansy/src/http/span.rs
> +/// Parses a request or response body.
I assume dechunking will be later called from inside this method, so we are passing in a `message body`.
```suggestion
/// Parses a request or response message body.
```

2024-02-08 07:29 UTC, themighty1 commented on spansy/src/http/span.rs
> +/// * `range` - The range of the body in the source bytes.
```suggestion
/// * `range` - The range of the message body in the source bytes.
```

2024-02-08 07:29 UTC, themighty1 commented on spansy/src/http/types.rs
>  pub struct Body {
Can we change the `Body`'s doc comment to read
/// An HTTP request or response payload body.

2024-02-08 07:29 UTC, themighty1 commented on spansy/src/http/types.rs
> +/// An HTTP request or response body content.
```suggestion
/// An HTTP request or response payload body content.
```

2024-02-08 19:34 UTC, sinui0 commented on spansy/src/http/span.rs
> +            .headers_with_name("Content-Type")
I'm a bit torn on doing this. This crate is for _parsing_ spans of HTTP fields, not necessarily _validating_ them (at least not past what is minimally required to complete parsing). A message with a duplicate `Content-Type` header is considered malformed, but is still syntactically valid. I'm open to discussion on whether to we should put validation into scope of this crate too, but I don't want to block this PR on it.

2024-02-08 19:40 UTC, merged