Added code to invert ranges
tlsnotary/tlsn-utils pull request #3
Opened 2023-09-04 15:46 UTC by th4s

This PR adds a function which allows to invert ranges.

2023-09-05 22:55 UTC, sinui0 requested changes
Perhaps we should move this to `spansy`? I expect this functionality to be exclusively used with spans. It could be implemented as a method on `Span`

2023-09-05 22:55 UTC, sinui0 commented on utils/src/invert_range.rs
> +        }
This is O(n^2). We can probably do better with a sort:

pseudo code:

```rust
ranges_to_remove.sort_by(|r| r.start);
assert!(ranges_to_remove.windows(2).all(|(l, r)| r.start > l.start && r.end > l.end));
```

2023-09-05 22:55 UTC, sinui0 commented on utils/src/invert_range.rs
> +    }
With `ranges_to_remove` sorted you can just operate on the tail

```suggestion
    let mut inverted = Vec::with_capacity(ranges_to_remove.len() + 1);
    inverted.push(original_range.clone());
    for remove in ranges_to_remove {
        let tail = inverted.last_mut().unwrap();
        
        tail.end = remove.start;
        
        inverted.push(remove.end..original_range.end);
    }
```

2023-09-05 22:55 UTC, sinui0 commented on utils/src/invert_range.rs
> +    inverted.retain(|r| r.start != r.end);
This should be unneeded with above

2023-09-06 10:26 UTC, th4s commented
I also thought about moving this to spansy. What kept me from doing it, was that this works with ranges and has nothing to do with spanning. The question is probably if this functionality will be exposed by `tlsn` or by `spansy`.

Considering the performance, I did not pay much attention to it, but makes sense. I will add it.

2023-09-06 11:25 UTC, th4s commented on utils/src/invert_range.rs
> +    }
very nice! :+1:

2023-09-06 11:29 UTC, th4s commented on utils/src/invert_range.rs
> +    inverted.retain(|r| r.start != r.end);
This is still needed if `tail.end == remove.start`.

2023-09-06 21:05 UTC, sinui0 approved these changes

2023-09-08 06:13 UTC, themighty1 commented
Is the plan to use this approach or the `rangetools` crate?

2023-09-21 04:16 UTC, th4s commented
This is superseeded by #4

2023-09-21 04:16 UTC, closed without merging