Added unbounded memory channels
tlsnotary/tlsn-utils pull request #37
Opened 2024-08-14 09:58 UTC by n-lebel

This PR adds unbounded memory channels in the helpers, wrapping `mpsc::UnboundedSender` and `mpsc::UnboundedReceiver`.

2024-08-15 06:57 UTC, th4s commented
Hey thanks for the PR. Is there some backstory on the reason for this PR?

2024-08-15 08:26 UTC, n-lebel commented
> Hey thanks for the PR. Is there some backstory on the reason for this PR?

I'm using `serio` traits for an internal project and needed to replace some `UnboundedSender/Receiver`s with a type that implemented these traits. Seemed reasonable to open a PR here as I assume it could be useful to others too.

2024-08-21 10:02 UTC, th4s requested changes
If we want to merge this, we should make sure that `MemoryDuplex` also works with the unbounded versions you introduced. Probably something like this
```rust
pub struct MemoryDuplex<Si, St> {
    sink: Si,
    stream: St
  }
```

2024-08-21 10:02 UTC, th4s commented on CHANGELOG.md
> +`UnboundedMemorySink` and `UnboundedMemoryStream` mirroring the `MemorySink` and `MemoryStream` wrappers of `futures::mpsc::{Sender, Receiver} for `futures::mpsc::{UnboundedSender, UnboundedReceiver}
```suggestion
`UnboundedMemorySink` and `UnboundedMemoryStream` mirroring the `MemorySink` and `MemoryStream` wrappers of `futures::mpsc::{Sender, Receiver}` for `futures::mpsc::{UnboundedSender, UnboundedReceiver}`.
```

2024-08-21 10:02 UTC, th4s commented on serio/src/channel.rs
> +/// An Unbounded memory stream that can be used to receive any deserializable type from the sender.
```suggestion
/// An unbounded memory stream that can be used to receive any deserializable type from the sender.
```

2024-11-22 09:45 UTC, n-lebel commented
@th4s Would an `UnboundedMemoryDuplex` also work for you? Would entail the fewest changes as I see it

2024-11-25 14:54 UTC, sinui0 requested changes
lgtm modulo the function doc. Thanks!

2024-11-25 14:54 UTC, sinui0 commented on serio/src/channel.rs
> +/// Creates a new memory channel with the specified buffer size.
```suggestion
/// Creates a new unbounded memory channel.
```

2024-11-25 16:09 UTC, sinui0 approved these changes
ty!

2024-11-25 16:14 UTC, merged