feat(utils): additional set operations
tlsnotary/tlsn-utils pull request #39
Opened 2024-09-02 01:45 UTC by sinui0

Closes #8 

This PR adds the set intersection operation and additional subset implementations. I've also removed the superset operation which is redundant with subset.

Exhaustively testing these operations is difficult so I've added more fuzz targets, and included a proof for set-set intersection.

2024-09-04 09:22 UTC, th4s requested changes
Good work :+1:

~~I think there is an issue with the subset implementation.~~
 
EDIT: I forgot about the invariants of `RangeSet`.

2024-09-04 09:22 UTC, th4s commented on utils/src/range/subset.rs
> +            }
There is also the case of `self.end <= other.start`.

2024-09-04 09:22 UTC, th4s commented on utils/src/range/subset.rs
> +        false
Shouldn't this whole block rather be:
```rust
for other in &other.ranges {
  if self.is_subset(other) {
    return true;
  }
}
false
```

2024-09-04 09:28 UTC, th4s approved these changes

2024-09-05 02:29 UTC, merged

2024-09-09 12:20 UTC, themighty1 commented
ACK